### ISSUE TITLE
Adnmin:: Login/Pass change - wtf

### ISSUE THREAD

**Issue by AndrwFn** [unclechu/sibtek-site#6]
Labels;
Headers;
Active menu Item;

**Comment by unclechu** [comment]
What the fuck?

```
Labels;
Headers;
Active menu Item;
```

It's three different issues. And haven't ant connection with this issue.

**Comment by AndrwFn** [comment]
commit be89e23f492f36306e8749e916f203942008ab9d

**Comment by AndrwFn** [comment]
https://github.com/unclechu/sibtek-site/commit/be89e23f492f36306e8749e916f203942008ab9d
